# Generated by Django 2.2.4 on 2019-08-05 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190805_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='size',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.ItemSize'),
        ),
    ]
