# Generated by Django 2.2.4 on 2019-08-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190805_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='size',
        ),
    ]
